name: Comprobador de Precios InkaFarma

on:
  workflow_dispatch:
  schedule:
    - cron: '23 3 * * *' # Todos los días a las 03:21 UTC (que son las 22:21 en UTC-5)

jobs:
  check_price_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 requests-html "lxml[html_clean]"

      - name: Ejecutar el script de comprobación de precios
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_APP_PASSWORD: ${{ secrets.SENDER_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: python main.py # <--- CAMBIO AQUÍ
