name: Comprobador de Precios InkaFarma

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *' # Tu configuración actual (ej. 22:00 UTC)

jobs:
  check_price_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4 # SIN EL 'with:' si no es necesario

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 requests-html "lxml[html_clean]"

      - name: Ejecutar el script de comprobación de precios
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_APP_PASSWORD: ${{ secrets.SENDER_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: python main.py

      - name: Auto-commit del archivo de estado (si cambió)
        uses: stefanzweifel/git-auto-commit-action@v5 # O la última versión
        with:
          commit_message: "Estado: Actualizar precios de productos y ofertas"
          file_pattern: "product_states.json" # Solo hacer commit de este archivo si cambia
          # Opcional: añadir un autor y email específicos para el commit del bot
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
          # Opciones para hacer push:
          push_options: '--force' # Considerar si es necesario, o gestionar ramas/PRs
                                  # Por ahora, un push directo a la rama principal es lo más simple
                                  # para este caso de uso.
