name: Comprobador de Precios InkaFarma

on:
  workflow_dispatch: # Permite ejecución manual
  schedule:
    # Se ejecuta todos los días a las 23:00 UTC (que son las 18:00 en UTC-5)
    - cron: '0 23 * * *'

jobs:
  check_price_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # O la versión que estés usando

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 requests-html "lxml[html_clean]"

      - name: Ejecutar el script de comprobación de precios
        run: python check_price.py
