name: Comprobador de Precios InkaFarma

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' # Todos los días a las 08:00 UTC

jobs:
  check_price_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          # Añadimos lxml[html_clean] para asegurar que la dependencia de requests-html esté completa
          pip install requests beautifulsoup4 requests-html "lxml[html_clean]"

      - name: Ejecutar el script de comprobación de precios
        run: python check_price.py
