name: Comprobador de Precios InkaFarma

on:
  # Permite ejecutar este workflow manualmente desde la pestaña Actions en GitHub
  workflow_dispatch:

  # Programa la ejecución del workflow
  schedule:
    # Se ejecuta todos los días a las 08:00 UTC (puedes ajustar la hora)
    # Formato CRON: minuto hora dia-del-mes mes dia-de-la-semana
    # Ver https://crontab.guru/ para ayuda con la sintaxis cron
    - cron: '0 8 * * *'

jobs:
  check_price_job:
    runs-on: ubuntu-latest # Usa la última versión de Ubuntu disponible en GitHub Actions

    steps:
      # 1. Clona tu repositorio para que el workflow pueda acceder al script
      - name: Checkout del código
        uses: actions/checkout@v4 # O la última versión disponible

      # 2. Configura el entorno de Python
      - name: Configurar Python
        uses: actions/setup-python@v5 # O la última versión disponible
        with:
          python-version: '3.10' # Puedes usar 3.8, 3.9, 3.10, 3.11, etc.

      # 3. Instala las dependencias necesarias para el script
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 4. Ejecuta tu script de Python
      - name: Ejecutar el script de comprobación de precios
        run: python check_price.py
